# Generated by Django 5.1.11 on 2025-06-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(blank=True, choices=[('registration', 'Registration'), ('tuition', 'Tuition'), ('sports', 'Sports'), ('lab', 'Lab Fees'), ('library', 'Library')], max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionFeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.IntegerField()),
                ('language_version', models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('arabic', 'Arabic')], max_length=100)),
                ('total_admission_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('language_version', models.CharField(blank=True, choices=[('bangla', 'Bangla'), ('english', 'English'), ('arabic', 'Arabic')], max_length=20, null=True)),
                ('monthly_tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('monthly_tuition_fee_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admission_fee_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('remaining_due', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('bikash', 'Bikash'), ('rocket', 'Rocket'), ('nagad', 'Nagad'), ('bank', 'Bank')], max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('monthly_tuition_fee_payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial-paid', 'Partial paid'), ('due', 'Due')], default='due', max_length=20)),
                ('admission_fee_payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial-paid', 'Partial paid'), ('due', 'Due')], default='due', max_length=20)),
                ('payment_status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial-paid', 'Partial paid'), ('due', 'Due')], max_length=20, null=True)),
                ('is_all_clear', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('tuition_fees', 'Tuition Fee'), ('admission_fee', 'Admission Fee')], max_length=30)),
                ('tuition_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('tran_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial-paid', 'Partial paid'), ('due', 'Due')], default='due', max_length=20)),
                ('admission_fee_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_fee_items', to='payments.admissionfee')),
            ],
        ),
    ]
