# Generated by Django 5.1.15 on 2026-01-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('school_management', '0002_initial'),
        ('students', '0001_initial'),
        ('university_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionfeepayment',
            name='admission_fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_payments', to='students.admissionfeeassignment'),
        ),
        migrations.AddField(
            model_name='admissionfeepayment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_admission_payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='admissionfeepolicy',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_management.academicsession'),
        ),
        migrations.AddField(
            model_name='admissionfeepolicy',
            name='language_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management.language'),
        ),
        migrations.AddField(
            model_name='admissionfeepolicy',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_management.program'),
        ),
        migrations.AddField(
            model_name='admissionfeepolicy',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_admission', to='school_management.academicclass'),
        ),
        migrations.AddField(
            model_name='admissionfee',
            name='admission_fee_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_fees', to='payments.admissionfeepolicy'),
        ),
        migrations.AddField(
            model_name='examfeepayment',
            name='exam_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_fee_payments', to='students.examfee'),
        ),
        migrations.AddField(
            model_name='examfeepayment',
            name='exam_fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_fee_payments', to='students.examfeeassignment'),
        ),
        migrations.AddField(
            model_name='examfeepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_fee_payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='admissionfee_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_fee_policy', to='payments.admissionfeepolicy'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures_class', to='school_management.academicclass'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionfeepayment',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_fee_structure', to='payments.feestructure'),
        ),
        migrations.AddField(
            model_name='hostelroompayment',
            name='hostel_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_payments', to='students.hostelassignment'),
        ),
        migrations.AddField(
            model_name='hostelroompayment',
            name='hostel_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_room_payments', to='students.hostelroom'),
        ),
        migrations.AddField(
            model_name='hostelroompayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hostel_payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='other_fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_fee_payments', to='students.otherfee'),
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_fee_students', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='admission_fee_items',
            field=models.ManyToManyField(blank=True, related_name='payments', to='payments.admissionfee'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='admission_fee_items',
            field=models.ManyToManyField(blank=True, to='payments.admissionfee'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='admission_fee_payment_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_admission', to='students.admissionfeeassignment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='admission_payments',
            field=models.ManyToManyField(blank=True, related_name='invoice_adissions', to='payments.admissionfeepayment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='exam_fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.examfeeassignment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='exam_payments',
            field=models.ManyToManyField(blank=True, related_name='invoice_exam_fees', to='payments.examfeepayment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='hostel_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_hostels', to='students.hostelassignment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='hostel_payments',
            field=models.ManyToManyField(blank=True, related_name='invoice_hostels', to='payments.hostelroompayment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='other_fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_otherfees', to='students.otherfee'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='other_payments',
            field=models.ManyToManyField(blank=True, related_name='invoice_other_fees', to='payments.otherfeepayment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_students', to='students.student'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='student_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='transport_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_transports', to='students.transportassignment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='tution_payment_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_tuition', to='students.tuitionfeeassignment'),
        ),
        migrations.AddField(
            model_name='transportpayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transport_payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='transportpayment',
            name='transport_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_payments', to='students.transportassignment'),
        ),
        migrations.AddField(
            model_name='transportpayment',
            name='transport_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_route_payments', to='students.transportroute'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='transport_payments',
            field=models.ManyToManyField(blank=True, related_name='invoice_transports', to='payments.transportpayment'),
        ),
        migrations.AddField(
            model_name='tuitionfeepayment',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuition_fee_structure', to='payments.feestructure'),
        ),
        migrations.AddField(
            model_name='tuitionfeepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tuition_payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='tuitionfeepayment',
            name='tuition_fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_payments', to='students.tuitionfeeassignment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='tuition_payments',
            field=models.ManyToManyField(blank=True, related_name='invoice_tuitions', to='payments.tuitionfeepayment'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionfeepolicy',
            unique_together={('academic_year', 'student_class', 'language_version')},
        ),
        migrations.AlterUniqueTogether(
            name='admissionfee',
            unique_together={('admission_fee_policy', 'fee_type')},
        ),
        migrations.AlterUniqueTogether(
            name='examfeepayment',
            unique_together={('student', 'exam_fee')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'student_class', 'language_version')},
        ),
        migrations.AlterUniqueTogether(
            name='hostelroompayment',
            unique_together={('student', 'hostel_room', 'academic_year', 'month')},
        ),
    ]
