# Generated by Django 5.1.11 on 2025-06-20 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('school_management', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionfeepolicy',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_admission', to='school_management.academicclass'),
        ),
        migrations.AddField(
            model_name='admissionfee',
            name='admission_fee_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_fees', to='payments.admissionfeepolicy'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='admissionfee_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_fee_policy', to='payments.admissionfeepolicy'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures_class', to='school_management.academicclass'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='admissionfeepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_fee_payments', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='admission_fee_items',
            field=models.ManyToManyField(blank=True, to='payments.admissionfee'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionfeepolicy',
            unique_together={('academic_year', 'student_class', 'language_version')},
        ),
        migrations.AlterUniqueTogether(
            name='admissionfee',
            unique_together={('admission_fee_policy', 'fee_type')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'student_class', 'language_version')},
        ),
        migrations.AlterUniqueTogether(
            name='admissionfeepayment',
            unique_together={('payment', 'admission_fee_item')},
        ),
    ]
