# Generated by Django 5.1.15 on 2026-01-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('SSLCOMMERZE', 'SSL Commerze'), ('Bikash', 'Bikash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket'), ('CREDIT-CARD', 'Credit card'), ('Cash', 'Cash')], max_length=50, null=True),
        ),
    ]
