# Generated by Django 5.1.11 on 2025-06-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admission_fee_items',
            field=models.ManyToManyField(blank=True, related_name='payments', to='payments.admissionfee'),
        ),
    ]
