# Generated by Django 5.1.15 on 2026-01-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('payments', '0002_initial'),
        ('school_management', '0002_initial'),
        ('students', '0001_initial'),
        ('university_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelassignment',
            name='varsity_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_hostel_assignments', to='university_management.varsitystudentenrollment'),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_rooms', to='students.hostel'),
        ),
        migrations.AddField(
            model_name='hostelassignment',
            name='hostel_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.hostelroom'),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms_type', to='students.roomtype'),
        ),
        migrations.AddField(
            model_name='student',
            name='attendance_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancepolicy'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardians', to='students.guardian'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherfee',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_fees_students', to='students.student'),
        ),
        migrations.AddField(
            model_name='hostelassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_hostel_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='examfeeassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_examfee_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='admissionfeeassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_admission_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management.academicclass'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='attendance_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_policy', to='attendance.attendancepolicy'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='feestructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_fees', to='payments.feestructure'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management.gender'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management.language'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management.shift'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherfee',
            name='student_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_other_fees', to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='hostelassignment',
            name='student_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_assignments', to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='admissionfeeassignment',
            name='student_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_assignments', to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_transport_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='student_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='varsity_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_transport_assignments', to='university_management.varsitystudentenrollment'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.transportroute'),
        ),
        migrations.AddField(
            model_name='tuitionfeeassignment',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.feestructure'),
        ),
        migrations.AddField(
            model_name='tuitionfeeassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_tuition_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='tuitionfeeassignment',
            name='student_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_assignments', to='students.studentenrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='examfee',
            unique_together={('academic_year', 'student_class', 'language_version', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='hostelroom',
            unique_together={('hostel', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('roll_number', 'academic_year', 'section')},
        ),
    ]
