# Generated by Django 5.1.15 on 2026-01-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(blank=True, choices=[('school', 'school'), ('college', 'college'), ('university', 'university')], max_length=100, null=True),
        ),
    ]
