# Generated by Django 5.1.15 on 2026-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpolicy',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('Tuition_fee', 'Tuition Fee'), ('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
