# Generated by Django 5.1.15 on 2026-01-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('', ''), ('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Teaching', 'Teaching'), ('Engineering', 'Engineering'), ('Technology', 'Technology'), ('Operations', 'Operations'), ('Planning', 'Planning'), ('Information Technology', 'Information Technology'), ('Customer Support', 'Customer Support'), ('Research & Development', 'Research & Development'), ('Legal & Compliance', 'Legal & Compliance'), ('SCM', 'Supply Chain Management (SCM)'), ('Logistics', 'Logistics'), ('Quality Assurance', 'Quality Assurance'), ('Business Control', 'Business Control'), ('Design and Creative', 'Design and Creative'), ('Public Relations', 'Public Relations'), ('Corporate Strategy and Planning', 'Corporate Strategy and Planning'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Production', 'Production'), ('Admin', 'Admin'), ('HR', 'Human Resources'), ('Training and Development', 'Training and Development'), ('Event Management', 'Event Management'), ('Environmental, Social, and Governance (ESG)', 'Environmental, Social, and Governance (ESG)'), ('Health and Safety', 'Health and Safety'), ('Business Development', 'Business Development'), ('Facilities Management', 'Facilities Management'), ('Investor Relations', 'Investor Relations'), ('Medical Healthcare', 'Medical Healthcare'), ('Procurement', 'Procurement'), ('Security', 'Security'), ('Learning and Development', 'Learning and Development'), ('Corporate Communications', 'Corporate Communications'), ('Sustainability', 'Sustainability')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('arts', 'Arts'), ('commerce', 'Commerce'), ('science', 'Science'), ('general', 'General')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('category', models.CharField(choices=[('background', 'Background Image'), ('event', 'Event Photo'), ('notice', 'Notice Board'), ('activity', 'School Activities')], max_length=20)),
                ('image', models.ImageField(upload_to='school_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('', ''), ('Chairman', 'Chairman'), ('MD', 'MD'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('COO', 'COO'), ('CTO', 'CTO'), ('CIO', 'CIO'), ('CHRO', 'CHRO'), ('CMO', 'CMO'), ('CSO', 'CSO'), ('CLO', 'CLO'), ('CDO', 'CDO'), ('Director', 'Director'), ('Executive Director', 'Executive Director'), ('HOD', 'HOD'), ('AVP', 'AVP'), ('VP', 'VP'), ('Senior VP', 'Senior VP'), ('General Manager', 'General Manager'), ('DGM', 'DGM'), ('GM', 'GM'), ('SrGM', 'SrGM'), ('Manager', 'Manager'), ('Sr.Manager', 'Sr.Manager'), ('Assistant Manager', 'Assistant Manager'), ('Team Lead', 'Team Lead'), ('Supervisor', 'Supervisor'), ('Coordinator', 'Coordinator'), ('HSS_manager', 'HSS_manager'), ('Specialist', 'Specialist'), ('Senior Specialist', 'Senior Specialist'), ('Officer', 'Officer'), ('Executive Officer', 'Executive Officer'), ('Project Manager', 'Project Manager'), ('Program Manager', 'Program Manager'), ('Consultant', 'Consultant'), ('Advisor', 'Advisor'), ('Engineer', 'Engineer'), ('Senior Engineer', 'Senior Engineer'), ('Software Developer', 'Software Developer'), ('System Analyst', 'System Analyst'), ('Data Scientist', 'Data Scientist'), ('IT Specialist', 'IT Specialist'), ('Architect', 'Architect'), ('Driver', 'Driver'), ('Peon', 'Peon'), ('Office Assistant', 'Office Assistant'), ('Receptionist', 'Receptionist'), ('Clerk', 'Clerk'), ('Secretary', 'Secretary'), ('General Staff', 'General Staff'), ('Personal Assistant', 'Personal Assistant'), ('Administrative Officer', 'Administrative Officer'), ('Sales Manager', 'Sales Manager'), ('Sales Executive', 'Sales Executive'), ('Marketing Manager', 'Marketing Manager'), ('Marketing Executive', 'Marketing Executive'), ('Business Development Manager', 'Business Development Manager'), ('Account Manager', 'Account Manager'), ('HR Manager', 'HR Manager'), ('HR Executive', 'HR Executive'), ('Recruiter', 'Recruiter'), ('Training Manager', 'Training Manager'), ('Payroll Specialist', 'Payroll Specialist'), ('Finance Manager', 'Finance Manager'), ('Accountant', 'Accountant'), ('Auditor', 'Auditor'), ('Legal Advisor', 'Legal Advisor'), ('Compliance Officer', 'Compliance Officer'), ('Operations Manager', 'Operations Manager'), ('Logistics Manager', 'Logistics Manager'), ('Warehouse Supervisor', 'Warehouse Supervisor'), ('Procurement Officer', 'Procurement Officer'), ('Inventory Manager', 'Inventory Manager'), ('Research Scientist', 'Research Scientist'), ('R&D Manager', 'R&D Manager'), ('Product Developer', 'Product Developer'), ('Principle', 'Principle'), ('Vice-Principle', 'Vice Principle'), ('Teacher', 'Teacher'), ('Lecturer', 'Lecturer'), ('Professor', 'Professor'), ('Trainer', 'Trainer'), ('Coach', 'Coach'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Lab Technician', 'Lab Technician'), ('Medical Assistant', 'Medical Assistant'), ('Volunteer', 'Volunteer'), ('Intern', 'Intern'), ('Trainee', 'Trainee')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['academic_class', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('institution_type', models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('polytechnic', 'Polytechnic'), ('madrasa', 'Madrasa'), ('training', 'Training Institute'), ('medical', 'Medical / Nursing')], max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('date_of_establishment', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(blank=True, null=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='school_management.academicclass')),
            ],
        ),
    ]
