# Generated by Django 5.1.11 on 2025-06-21 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='e.g. 25.00 for 25%', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ShareholderInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_invested', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('share_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='finance.shareholders')),
            ],
        ),
    ]
