# Generated by Django 5.1.15 on 2026-01-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_expense_name_purchaseorder_purchaseitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='is_asset',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
