# Generated by Django 5.1.11 on 2025-06-20 10:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('biometric_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('parent', 'Parent'), ('staff', 'Staff'), ('superadmin', 'SuperAdmin')], default='student', max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user_department', models.CharField(blank=True, choices=[('', ''), ('Engineering', 'Engineering'), ('Technology', 'Technology'), ('Operations', 'Operations'), ('Planning', 'Planning'), ('Information Technology', 'Information Technology'), ('Customer Support', 'Customer Support'), ('Research & Development', 'Research & Development'), ('Legal & Compliance', 'Legal & Compliance'), ('SCM', 'Supply Chain Management (SCM)'), ('Logistics', 'Logistics'), ('Quality Assurance', 'Quality Assurance'), ('Business Control', 'Business Control'), ('Design and Creative', 'Design and Creative'), ('Public Relations', 'Public Relations'), ('Corporate Strategy and Planning', 'Corporate Strategy and Planning'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Production', 'Production'), ('Admin', 'Admin'), ('HR', 'Human Resources'), ('Training and Development', 'Training and Development'), ('Event Management', 'Event Management'), ('Environmental, Social, and Governance (ESG)', 'Environmental, Social, and Governance (ESG)'), ('Health and Safety', 'Health and Safety'), ('Business Development', 'Business Development'), ('Facilities Management', 'Facilities Management'), ('Investor Relations', 'Investor Relations'), ('Medical Healthcare', 'Medical Healthcare'), ('Procurement', 'Procurement'), ('Security', 'Security'), ('Learning and Development', 'Learning and Development'), ('Corporate Communications', 'Corporate Communications'), ('Sustainability', 'Sustainability')], max_length=100, null=True)),
                ('user_position', models.CharField(blank=True, choices=[('', ''), ('Chairman', 'Chairman'), ('MD', 'MD'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('COO', 'COO'), ('CTO', 'CTO'), ('CIO', 'CIO'), ('CHRO', 'CHRO'), ('CMO', 'CMO'), ('CSO', 'CSO'), ('CLO', 'CLO'), ('CDO', 'CDO'), ('Director', 'Director'), ('Executive Director', 'Executive Director'), ('HOD', 'HOD'), ('AVP', 'AVP'), ('VP', 'VP'), ('Senior VP', 'Senior VP'), ('General Manager', 'General Manager'), ('DGM', 'DGM'), ('GM', 'GM'), ('SrGM', 'SrGM'), ('Manager', 'Manager'), ('Sr.Manager', 'Sr.Manager'), ('Assistant Manager', 'Assistant Manager'), ('Team Lead', 'Team Lead'), ('Supervisor', 'Supervisor'), ('Coordinator', 'Coordinator'), ('HSS_manager', 'HSS_manager'), ('Specialist', 'Specialist'), ('Senior Specialist', 'Senior Specialist'), ('Officer', 'Officer'), ('Executive Officer', 'Executive Officer'), ('Project Manager', 'Project Manager'), ('Program Manager', 'Program Manager'), ('Consultant', 'Consultant'), ('Advisor', 'Advisor'), ('Engineer', 'Engineer'), ('Senior Engineer', 'Senior Engineer'), ('Software Developer', 'Software Developer'), ('System Analyst', 'System Analyst'), ('Data Scientist', 'Data Scientist'), ('IT Specialist', 'IT Specialist'), ('Architect', 'Architect'), ('Driver', 'Driver'), ('Peon', 'Peon'), ('Office Assistant', 'Office Assistant'), ('Receptionist', 'Receptionist'), ('Clerk', 'Clerk'), ('Secretary', 'Secretary'), ('General Staff', 'General Staff'), ('Personal Assistant', 'Personal Assistant'), ('Administrative Officer', 'Administrative Officer'), ('Sales Manager', 'Sales Manager'), ('Sales Executive', 'Sales Executive'), ('Marketing Manager', 'Marketing Manager'), ('Marketing Executive', 'Marketing Executive'), ('Business Development Manager', 'Business Development Manager'), ('Account Manager', 'Account Manager'), ('HR Manager', 'HR Manager'), ('HR Executive', 'HR Executive'), ('Recruiter', 'Recruiter'), ('Training Manager', 'Training Manager'), ('Payroll Specialist', 'Payroll Specialist'), ('Finance Manager', 'Finance Manager'), ('Accountant', 'Accountant'), ('Auditor', 'Auditor'), ('Legal Advisor', 'Legal Advisor'), ('Compliance Officer', 'Compliance Officer'), ('Operations Manager', 'Operations Manager'), ('Logistics Manager', 'Logistics Manager'), ('Warehouse Supervisor', 'Warehouse Supervisor'), ('Procurement Officer', 'Procurement Officer'), ('Inventory Manager', 'Inventory Manager'), ('Research Scientist', 'Research Scientist'), ('R&D Manager', 'R&D Manager'), ('Product Developer', 'Product Developer'), ('Teacher', 'Teacher'), ('Lecturer', 'Lecturer'), ('Professor', 'Professor'), ('Trainer', 'Trainer'), ('Coach', 'Coach'), ('Student', 'Student'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Lab Technician', 'Lab Technician'), ('Medical Assistant', 'Medical Assistant'), ('Volunteer', 'Volunteer'), ('Intern', 'Intern'), ('Trainee', 'Trainee')], max_length=100, null=True)),
                ('photo_id', models.ImageField(blank=True, null=True, upload_to='user_photo')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
