# Generated by Django 5.1.15 on 2026-01-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_type',
            field=models.CharField(blank=True, choices=[('school', 'school'), ('college', 'college'), ('university', 'university')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_type',
            field=models.CharField(blank=True, choices=[('school', 'school'), ('college', 'college'), ('university', 'university')], max_length=100, null=True),
        ),
    ]
