# Generated by Django 5.1.15 on 2026-01-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_student_type_customuser_teacher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('parent', 'Parent'), ('staff', 'Staff'), ('superadmin', 'SuperAdmin'), ('management', 'Management'), ('accounts_finance', 'Accounts & Finance')], default='student', max_length=30),
        ),
    ]
