# Generated by Django 5.1.11 on 2025-06-20 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('message_type', models.CharField(blank=True, choices=[('Attendance', 'Attendance'), ('Result', 'Result'), ('Fee', 'Fee'), ('General', 'General')], max_length=50, null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, choices=[('attendance', 'Attendance'), ('payment-due', 'Payment_due'), ('notice', 'Notice'), ('general', 'General')], max_length=20, null=True)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_group', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='message_videos/')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.communicationmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, choices=[('', ''), ('Chairman', 'Chairman'), ('MD', 'MD'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('COO', 'COO'), ('CTO', 'CTO'), ('CIO', 'CIO'), ('CHRO', 'CHRO'), ('CMO', 'CMO'), ('CSO', 'CSO'), ('CLO', 'CLO'), ('CDO', 'CDO'), ('Director', 'Director'), ('Executive Director', 'Executive Director'), ('HOD', 'HOD'), ('AVP', 'AVP'), ('VP', 'VP'), ('Senior VP', 'Senior VP'), ('General Manager', 'General Manager'), ('DGM', 'DGM'), ('GM', 'GM'), ('SrGM', 'SrGM'), ('Manager', 'Manager'), ('Sr.Manager', 'Sr.Manager'), ('Assistant Manager', 'Assistant Manager'), ('Team Lead', 'Team Lead'), ('Supervisor', 'Supervisor'), ('Coordinator', 'Coordinator'), ('HSS_manager', 'HSS_manager'), ('Specialist', 'Specialist'), ('Senior Specialist', 'Senior Specialist'), ('Officer', 'Officer'), ('Executive Officer', 'Executive Officer'), ('Project Manager', 'Project Manager'), ('Program Manager', 'Program Manager'), ('Consultant', 'Consultant'), ('Advisor', 'Advisor'), ('Engineer', 'Engineer'), ('Senior Engineer', 'Senior Engineer'), ('Software Developer', 'Software Developer'), ('System Analyst', 'System Analyst'), ('Data Scientist', 'Data Scientist'), ('IT Specialist', 'IT Specialist'), ('Architect', 'Architect'), ('Driver', 'Driver'), ('Peon', 'Peon'), ('Office Assistant', 'Office Assistant'), ('Receptionist', 'Receptionist'), ('Clerk', 'Clerk'), ('Secretary', 'Secretary'), ('General Staff', 'General Staff'), ('Personal Assistant', 'Personal Assistant'), ('Administrative Officer', 'Administrative Officer'), ('Sales Manager', 'Sales Manager'), ('Sales Executive', 'Sales Executive'), ('Marketing Manager', 'Marketing Manager'), ('Marketing Executive', 'Marketing Executive'), ('Business Development Manager', 'Business Development Manager'), ('Account Manager', 'Account Manager'), ('HR Manager', 'HR Manager'), ('HR Executive', 'HR Executive'), ('Recruiter', 'Recruiter'), ('Training Manager', 'Training Manager'), ('Payroll Specialist', 'Payroll Specialist'), ('Finance Manager', 'Finance Manager'), ('Accountant', 'Accountant'), ('Auditor', 'Auditor'), ('Legal Advisor', 'Legal Advisor'), ('Compliance Officer', 'Compliance Officer'), ('Operations Manager', 'Operations Manager'), ('Logistics Manager', 'Logistics Manager'), ('Warehouse Supervisor', 'Warehouse Supervisor'), ('Procurement Officer', 'Procurement Officer'), ('Inventory Manager', 'Inventory Manager'), ('Research Scientist', 'Research Scientist'), ('R&D Manager', 'R&D Manager'), ('Product Developer', 'Product Developer'), ('Teacher', 'Teacher'), ('Lecturer', 'Lecturer'), ('Professor', 'Professor'), ('Trainer', 'Trainer'), ('Coach', 'Coach'), ('Student', 'Student'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Lab Technician', 'Lab Technician'), ('Medical Assistant', 'Medical Assistant'), ('Volunteer', 'Volunteer'), ('Intern', 'Intern'), ('Trainee', 'Trainee')], max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tenant_photo/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='tenant_signature/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
