# Generated by Django 5.1.11 on 2025-06-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bKash', 'bKash'), ('Rocket', 'Rocket'), ('CreditCard', 'CreditCard'), ('PayPal', 'PayPal')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_redirect_url', models.URLField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_gatway.paymentsystem')),
            ],
        ),
    ]
