# Generated by Django 5.1.15 on 2026-01-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bKash', 'bKash'), ('Rocket', 'Rocket'), ('CreditCard', 'CreditCard'), ('PayPal', 'PayPal'), ('sslcommerz', 'SSLCommerz')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sandbox_url', models.URLField(blank=True, null=True)),
                ('production_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('store_id', models.CharField(blank=True, max_length=255, null=True)),
                ('store_password', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_redirect_url', models.URLField(blank=True, null=True)),
                ('extra_config', models.JSONField(blank=True, null=True)),
                ('payment_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_gatway.paymentsystem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
