# Generated by Django 5.1.11 on 2025-06-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('payment_gatway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='is_sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentsystem',
            name='production_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsystem',
            name='sandbox_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantpaymentconfig',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='paymentsystem',
            name='method',
            field=models.CharField(choices=[('bKash', 'bKash'), ('Rocket', 'Rocket'), ('CreditCard', 'CreditCard'), ('PayPal', 'PayPal'), ('sslcommerz', 'SSLCommerz')], max_length=50),
        ),
    ]
