# Generated by Django 5.1.11 on 2025-06-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('payment_gatway', '0002_paymentsystem_is_sandbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsystem',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='paymentsystem',
            name='is_sandbox',
        ),
        migrations.AddField(
            model_name='tenantpaymentconfig',
            name='extra_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantpaymentconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantpaymentconfig',
            name='is_sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantpaymentconfig',
            name='store_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantpaymentconfig',
            name='store_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsystem',
            name='method',
            field=models.CharField(choices=[('bKash', 'bKash'), ('Rocket', 'Rocket'), ('CreditCard', 'CreditCard'), ('PayPal', 'PayPal'), ('sslcommerz', 'SSLCommerz')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantpaymentconfig',
            name='payment_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_gatway.paymentsystem'),
        ),
        migrations.AlterField(
            model_name='tenantpaymentconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
