# Generated by Django 5.1.15 on 2026-01-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('attendance', '0001_initial'),
        ('school_management', '0002_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(blank=True, help_text='Class number or year number', null=True)),
                ('title', models.CharField(help_text='Class 5 / Year 2', max_length=50)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(max_length=10)),
                ('location', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_class_room_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('exam_type', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('improvement', 'Improvement')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academicsession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academiclevel')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fee_cleared', models.BooleanField(default=False)),
                ('admin_override', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to='university_management.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='admit_cards/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university_management.examregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_faculty', to='school_management.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_faculty_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Computer Science, Physics', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_user_department', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, help_text='Parent faculty (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_management.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school')),
            ],
            options={
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='BSc in CSE, HSC Science, SSC Science', max_length=150)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('duration_years', models.PositiveIntegerField(help_text='Total duration of the program in years')),
                ('total_credits', models.PositiveIntegerField(blank=True, help_text='Only applicable for credit-based programs', null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_management.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.program'),
        ),
        migrations.CreateModel(
            name='AdmissionFeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(blank=True, max_length=100, null=True)),
                ('total_admission_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.languageversion')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_fees_program_admission', to='university_management.program')),
            ],
            options={
                'unique_together': {('program', 'language')},
            },
        ),
        migrations.AddField(
            model_name='academiclevel',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program this level belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='university_management.program'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Subject code (e.g., MAT101, PHY-9)', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional syllabus summary', null=True)),
                ('is_credit_based', models.BooleanField(default=False, help_text='True for university credit subjects')),
                ('total_credit', models.DecimalField(blank=True, decimal_places=2, help_text='Default credit value (e.g., 3.00)', max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive subjects cannot be assigned')),
                ('per_credit_fee_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department offering this subject (mainly universities)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_management.department')),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty responsible for this subject (optional for schools)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_management.faculty')),
                ('institution', models.ForeignKey(help_text='Institution this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school_management.school')),
                ('program', models.ForeignKey(blank=True, help_text='B.SC.M.Sc, Diploma etc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_management.program')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_subject_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Semester 1, Final Term', max_length=50)),
                ('order', models.PositiveIntegerField(blank=True, help_text='Ordering within the level', null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academiclevel')),
            ],
            options={
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.PositiveIntegerField(default=50, help_text='Maximum students allowed in this subject offering')),
                ('is_compulsory', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.school')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academiclevel')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectoffering_program', to='university_management.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_management.term')),
            ],
            options={
                'unique_together': {('subject', 'level', 'term')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.term'),
        ),
        migrations.CreateModel(
            name='UniversityFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_credit_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_management.admissionfeepolicy')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.languageversion')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.program')),
            ],
        ),
        migrations.CreateModel(
            name='VarsityStudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academicsession')),
                ('attendance_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_policy_varsity', to='attendance.attendancepolicy')),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_management.universityfeestructure')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_management.languageversion')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_management.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varsity_student_enrollments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'academic_session', 'program')},
            },
        ),
        migrations.CreateModel(
            name='UniversityTermInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('total_subjects', models.PositiveIntegerField()),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=6)),
                ('per_credit_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academicsession')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academiclevel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_term_invoices', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.term')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_student_term_invoices', to='university_management.varsitystudentenrollment')),
            ],
            options={
                'unique_together': {('student', 'academic_session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='UniversityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuition_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('admission_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_posted', models.BooleanField(blank=True, default=False, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_payment_journal_entry', to='accounting.journalentry')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_term_payment', to='students.student')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='university_management.universityterminvoice')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_student_term_payments', to='university_management.varsitystudentenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTermRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('is_fee_cleared', models.BooleanField(default=False)),
                ('is_exam_eligible', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academiclevel')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_registrations', to='university_management.term')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_enrolled_registrations', to='university_management.varsitystudentenrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'term', 'level')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='academiclevel',
            unique_together={('institution', 'program', 'level_number')},
        ),
        migrations.CreateModel(
            name='StudentCGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cgpa_records', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'academic_session')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academicsession')),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_management.classroom')),
                ('subject_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varsity_subjetc_assignemnt', to='teachers.teacher')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varsity_teaching_assignments', to='university_management.subjectoffering')),
            ],
            options={
                'unique_together': {('subject_offering', 'subject_teacher')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='students.student')),
                ('term_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university_management.studenttermregistration')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_enrollment', to='university_management.subjectoffering')),
            ],
            options={
                'unique_together': {('student', 'subject_offering', 'term_registration')},
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='university_management.exam')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_exam_venue', to='university_management.classroom')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.subjectoffering')),
            ],
            options={
                'unique_together': {('exam', 'subject_offering')},
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_management.classroom')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_management.academicsession')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_schedules', to='teachers.teacher')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='university_management.subjectoffering')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('subject_offering', 'day_of_week', 'start_time', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='StudentTermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academicsession')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academiclevel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.term')),
            ],
            options={
                'unique_together': {('student', 'academic_session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=10)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('weighted_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.academicsession')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject_results', to='university_management.exam')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='students.student')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.subjectoffering')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.term')),
            ],
            options={
                'unique_together': {('student', 'subject_offering', 'term', 'academic_session')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('academic_session', 'program', 'level', 'term', 'exam_type')},
        ),
        migrations.CreateModel(
            name='AdmissionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(blank=True, choices=[('registration', 'Registration'), ('tuition', 'Tuition'), ('sports', 'Sports'), ('lab', 'Lab Fees'), ('library', 'Library')], max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_fee_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_admission_fees', to='university_management.admissionfeepolicy')),
                ('due_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_management.term')),
            ],
            options={
                'unique_together': {('admission_fee_policy', 'fee_type')},
            },
        ),
    ]
