# Generated by Django 5.1.15 on 2026-01-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taxpolicy_policy_type'),
        ('university_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitypayment',
            name='tax_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varsity_tax_policies', to='core.taxpolicy'),
        ),
    ]
